# Generated by Django 2.0.6 on 2018-07-19 06:00

import chains.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to=chains.models.chain_image_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_chains', to='accounts.Account')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ChainLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_accounts', to='accounts.Account')),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chains_liked', to='chains.Chain')),
            ],
            options={
                'ordering': ('-liked_at',),
            },
        ),
        migrations.CreateModel(
            name='ChainMention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentioned_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentioned_accounts', to='accounts.Account')),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chains_mentioned', to='chains.Chain')),
            ],
            options={
                'ordering': ('-mentioned_at',),
            },
        ),
        migrations.CreateModel(
            name='ChainTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chains_tagged', to='chains.Chain')),
            ],
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=144)),
            ],
        ),
        migrations.AddField(
            model_name='chaintag',
            name='hashtag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='included_tags', to='chains.Hashtag'),
        ),
        migrations.AddField(
            model_name='chain',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='like_to', through='chains.ChainLike', to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='chain',
            name='mentions',
            field=models.ManyToManyField(blank=True, null=True, related_name='mentioned_to', through='chains.ChainMention', to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='chain',
            name='parent_chain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_chains', to='chains.Chain'),
        ),
        migrations.AddField(
            model_name='chain',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='tagged_to', through='chains.ChainTag', to='chains.Hashtag'),
        ),
    ]
