# Generated by Django 2.0.6 on 2018-06-29 05:34

import chains.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20180629_0534'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to=chains.models.chain_image_path)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_chains', to='accounts.Account')),
            ],
        ),
        migrations.CreateModel(
            name='ChainMention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentioned_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentioned_account', to='accounts.Account')),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chains_mentioned', to='chains.Chain')),
            ],
        ),
        migrations.CreateModel(
            name='ChainTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=144)),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='chains.Chain')),
            ],
        ),
        migrations.AddField(
            model_name='chain',
            name='mentions',
            field=models.ManyToManyField(blank=True, null=True, related_name='mentioned_to', through='chains.ChainMention', to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='chain',
            name='parent_chain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_chains', to='chains.Chain'),
        ),
    ]
