# Generated by Django 2.0.6 on 2018-07-07 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180707_1508'),
        ('chains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChainLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_account', to='accounts.Account')),
            ],
        ),
        migrations.AlterField(
            model_name='chain',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chainmention',
            name='mentioned_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='chainlike',
            name='chain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chains_liked', to='chains.Chain'),
        ),
        migrations.AddField(
            model_name='chain',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='like_to', through='chains.ChainLike', to='accounts.Account'),
        ),
    ]
