# Generated by Django 2.0.6 on 2018-06-29 05:34

import accounts.models
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='banner',
            field=models.ImageField(blank=True, upload_to=accounts.models.banner_path),
        ),
        migrations.AlterField(
            model_name='account',
            name='follows',
            field=models.ManyToManyField(blank=True, null=True, related_name='followed_to', through='accounts.Follow', to='accounts.Account'),
        ),
        migrations.AlterField(
            model_name='account',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=accounts.models.thumbnail_path),
        ),
    ]
